<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10103" started-at="2019-10-05T07:53:11Z" finished-at="2019-10-05T07:53:22Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10103" started-at="2019-10-05T07:53:11Z" finished-at="2019-10-05T07:53:22Z">
      <class name="demo.backend.tests.POST_Call">
        <test-method status="PASS" signature="postData()[pri:0, instance:demo.backend.tests.POST_Call@6d4b1c02]" name="postData" is-config="true" duration-ms="28" started-at="2019-10-05T07:53:12Z" finished-at="2019-10-05T07:53:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postData -->
        <test-method status="PASS" signature="validateErrorMessage()[pri:1, instance:demo.backend.tests.POST_Call@6d4b1c02]" name="validateErrorMessage" duration-ms="3839" started-at="2019-10-05T07:53:12Z" finished-at="2019-10-05T07:53:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateErrorMessage -->
        <test-method status="PASS" signature="registerNewStations()[pri:2, instance:demo.backend.tests.POST_Call@6d4b1c02]" name="registerNewStations" duration-ms="2516" started-at="2019-10-05T07:53:15Z" finished-at="2019-10-05T07:53:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerNewStations -->
        <test-method status="PASS" signature="verifyStationRegistration()[pri:3, instance:demo.backend.tests.POST_Call@6d4b1c02]" name="verifyStationRegistration" duration-ms="1140" started-at="2019-10-05T07:53:18Z" finished-at="2019-10-05T07:53:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyStationRegistration -->
        <test-method status="PASS" signature="deleteStations()[pri:4, instance:demo.backend.tests.POST_Call@6d4b1c02]" name="deleteStations" duration-ms="1531" started-at="2019-10-05T07:53:19Z" finished-at="2019-10-05T07:53:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteStations -->
        <test-method status="FAIL" signature="valideErrorCodeForAlreadyDeletedStation()[pri:5, instance:demo.backend.tests.POST_Call@6d4b1c02]" name="valideErrorCodeForAlreadyDeletedStation" duration-ms="982" started-at="2019-10-05T07:53:21Z" finished-at="2019-10-05T07:53:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at demo.backend.tests.POST_Call.deleteAlreadyDeletedStationWithID(POST_Call.java:159)
at demo.backend.tests.POST_Call.valideErrorCodeForAlreadyDeletedStation(POST_Call.java:176)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- valideErrorCodeForAlreadyDeletedStation -->
      </class> <!-- demo.backend.tests.POST_Call -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
